server {
    listen 80;
    server_name clickteam.com.br www.clickteam.com.br;
    root /app/homepage;
    index index.html index.php;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name install.clickteam.com.br;
    root /app/integrations/install;
    index index.php;

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php:9000;
    }
}

server {
    listen 80;
    server_name api.clickteam.com.br;
    root /app/integrations/api;
    index index.php;

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php:9000;
    }
}

server {
    listen 80;
    server_name cdn.clickteam.com.br;
    root /app/integrations/cdn;
    index index.php;

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php:9000;
    }
}

server {
    listen 80;
    server_name voting.clickteam.com.br;
    root /app/integrations/voting;
    index index.php;

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php:9000;
    }
}

server {
    listen 80;
    server_name payment.clickteam.com.br;
    root /app/integrations/payment;
    index index.php;

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php:9000;
    }
}

server {
    listen 80;
    server_name ~^(?<world>[a-z0-9-]+)\.clickteam\.com\.br$;
    root /app/servers/$world/public;
    index index.php;

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php:9000;
    }
}
